_wandb:
    value:
        cli_version: 0.22.0
        e:
            70089x9pzdft55ljruor9nd8k51al9as:
                args:
                    - --config_file
                    - ../config/dense_config.yaml
                    - --generator_type
                    - EnhancedBetaTCVAE
                    - --discriminator_type
                    - UNet3P
                codePath: train_with_wandb.py
                codePathLocal: train_with_wandb.py
                email: 2745302895@qq.com
                executable: D:\Anaconda\envs\diverse_synth1\python.exe
                host: DESKTOP-7BBR1KD
                os: Windows-10-10.0.26200-SP0
                program: E:\diverse_synth\scripts\train_with_wandb.py
                python: CPython 3.9.23
                root: E:\diverse_synth\scripts
                startedAt: "2026-02-06T09:14:51.676299Z"
                writerId: 70089x9pzdft55ljruor9nd8k51al9as
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.23
            "5": 0.22.0
            "8":
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch_size:
    value: 64
device:
    value: cpu
epochs:
    value: 1000
learning_rate:
    value: dense_total
lr_decay_rates:
    value:
        - 0.1
        - 0.1
lr_decay_steps:
    value:
        - 1000
        - 2000
